name: firebase_ui_auth
description: Pre-built widgets library that are integrated with the variety of the Firebase Auth providers.
version: 1.2.4
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_auth

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  email_validator: ^2.0.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_dynamic_links: ^5.1.1
  firebase_ui_localizations: ^1.3.1
  firebase_ui_oauth: ^1.2.4
  firebase_ui_shared: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.

false_secrets:
  - '/example/**/google-services.json'
  - '/example/**/firebase_options.dart'
  - '/example/**/GoogleService-Info.plist'
  - 'example/lib/config.dart'

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.ui_auth
        pluginClass: FirebaseUiAuthPlugin
